### ISSUE TITLE
Published metrics in prometheus?

### ISSUE THREAD

**Issue by goncer** [enudler/artillery-plugin-prometheus#11]
Hi, I set up my environment following the tutorial described here:
https://medium.com/aeturnuminc/configure-prometheus-and-grafana-in-dockers-ff2a2b51aa1d
Basically I have 2 containers,
![image](https://user-images.githubusercontent.com/15139384/92231261-c7acd600-eeac-11ea-9b56-0976efda007e.png)

And they are working as expected.
I'm running the artillery with the following yml.

```
config:
  plugins:
    prometheus:
      testName: 'ImaTestRun'
      pushGatewayUrl: 'http://localhost:9090'
      environment: qa
      labels:
        target: 'http://foo.com/'
        scenario: Reports_Big

```
I'm a super-noob with Prometheus, would you mind helping me on finding the metrics in Prometheus or Grafana? 
What are the stats?

Many thanks!

![image](https://user-images.githubusercontent.com/15139384/92231547-2e31f400-eead-11ea-814f-a422c286bc75.png)

**Comment by enudler** [comment]
Hi

Please join predator workspace in slack
we will try to help you there

https://join.slack.com/t/predator-dev/shared_invite/enQtNjgwMzE2NjM3MDcyLTg5YTIwMGQyNjZlMjQ4MDNjOTk5YTkwMWYwNzJkOWFmM2QwOGY0ODc3MDU3MWRkYTAwMjRhMjBhOTM1MzFmMjU

**Comment by enudler** [comment]
Please join Predator slack
we will try to help you there:
https://join.slack.com/t/predator-dev/shared_invite/enQtNjgwMzE2NjM3MDcyLTg5YTIwMGQyNjZlMjQ4MDNjOTk5YTkwMWYwNzJkOWFmM2QwOGY0ODc3MDU3MWRkYTAwMjRhMjBhOTM1MzFmMjU

**Comment by goncer** [comment]
Manage to work:
Docker-compose file:
```
version: '3'
volumes:
    prometheus_data: {}
    pushgateway_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=1h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
      
  pushgateway:
    image: prom/pushgateway:v1.0.1
    volumes:
      - pushgateway_data:/data
    command:
      - --persistence.file=/data/pushgateway.data
      - --persistence.interval=1h
    ports: 
      - "9091:9091"
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
```

prometheus.yml
```
# my global config
global:
    scrape_interval:     15s # By default, scrape targets every 15 seconds.
    evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'Pushgateway'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
    - targets: ['pushgateway:9091']
```

Reference:
https://itnext.io/ephemeral-jobs-monitoring-using-prometheus-pushgateway-917b33486564

Howto:
1. Creeate dockerfile
2. Create a folder in the same folder as dockerfile called "prometheus"
3. Create a file "prometheus.yml" and paste the above content.
4. Run docker compose up.

Then configure the plugin with the setting: pushGatewayUrl: 'http://localhost:9091'
Done!
